const contactsData = {
  '025': [
    {name:'Fernanda Marques',title:'Head of Product Design',type:'Hiring Manager',linkedin:'https://www.linkedin.com/in/ferdimarques/',msg:'Saw Fever\'s DS role. You\'re post-DICE and Atom in 3 months — that\'s 4 brand surfaces that need a unified token layer. I owned that exact problem at Vio.com for 5 years: Token Studio + Figma + GitHub, multi-brand overrides, governance model. Happy to show the system: designsystemwizard.com'},
    {name:'Alessia De Rosa',title:'Senior Global Talent Acquisition Specialist',type:'Recruiter',linkedin:'https://es.linkedin.com/in/alessia-de-rosa-',msg:'Hi Alessia — applying for Fever\'s Senior Product Designer DS role. 10 years building multi-brand token systems (Vio.com, 5yr). Token Studio + Figma + GitHub in prod. WCAG + white-label theming = exact match to the JD. Portfolio: designsystemwizard.com — worth a call?'},
    {name:'Ana Traba de la Gándara',title:'Product Designer / Recruiting contact',type:'Peer',linkedin:'https://www.linkedin.com/in/anatraba/',msg:'Hey Ana — I saw Fever\'s DS role and noticed your name attached to it. I\'ve been in multi-brand design systems for 10+ years, most recently building a 5-brand token architecture at Vio.com (Token Studio + Figma + GitHub pipeline). Curious what the DS team looks like at Fever right now — portfolio: designsystemwizard.com'},
    {name:'Guillermo Rosewarne',title:'Product Designer & UX Engineer / Design System Lead',type:'Peer',linkedin:'https://www.linkedin.com/in/grosewarne/',msg:'Hey Guillermo — came across your work on Fever\'s DS. I\'m deep in multi-brand token systems myself — spent 5yr at Vio.com building a Token Studio + Figma + GitHub pipeline for 5 brands. I\'m looking at the DS role there and curious what the biggest challenges are right now — multi-device token distribution? Post-acquisition unification? Would genuinely enjoy a 20-min chat.'},
  ],
  '001': [
    {name:'Owen Choi',title:'Head of Talent Acquisition',type:'Recruiter',linkedin:'https://www.linkedin.com/in/owen-choi-831699a6/',msg:'Hi Owen — applying for the Senior Product Designer (Design Systems) role. 10 yrs DS ownership at Vio.com (travel SaaS) — built multi-brand token architecture, Token Studio → GitHub pipeline, RTL-first. Matches the "foundational owner" framing exactly. Happy to share portfolio. Michał'},
    {name:'Emmett Conroy',title:'Head of Design',type:'Hiring Manager',linkedin:'https://www.linkedin.com/in/emmett-conroy-a0354133/',msg:'Hi Emmett — saw the DS Designer role. I built Vio.com\'s design system from scratch over 5 yrs: token architecture, Figma→React pipeline, governance model. Curious what "foundational ownership" looks like in your team right now — happy to talk through how I\'d approach it. Michał'},
    {name:'Khrystyna Hala',title:'Tech Talent Acquisition',type:'Recruiter',linkedin:'https://www.linkedin.com/in/khryshala/',msg:'Hi Khrystyna — I\'m interested in the Senior Product Designer (Design Systems) role at Hostaway. 10+ yrs DS experience, last 5 at Vio.com (travel SaaS) — token architecture, Figma Variables, React collaboration. Portfolio: designsystemwizard.com. Would love to connect. Michał'},
    {name:'Aleksandar Buric',title:'Senior Product Designer',type:'Peer',linkedin:'https://rs.linkedin.com/in/alexandarburic',msg:'Hi Aleksandar — exploring the DS Designer role at Hostaway. I notice you\'re on the product design team there. I work in design systems too (Vio.com, travel SaaS) and curious about the current component workflow and what problems the new hire would actually be solving. Happy to swap notes.'},
  ],
  '002': [
    {name:'Ieva Visockytė',title:'Talent Acquisition Partner',type:'Recruiter',linkedin:'https://lt.linkedin.com/in/ieva-visockytė-b8892a166',msg:'Hi Ieva, I noticed Hostinger is hiring a Senior Design System Designer. I\'ve spent 10+ years in DS — 5 of those at Vio.com owning multi-brand token architecture across 5 product surfaces. Exact title match, EU citizen, CET. Happy to share portfolio. Worth a conversation?'},
    {name:'Milda Bandzevičiūtė',title:'Lead Web Designer',type:'Peer',linkedin:'https://www.linkedin.com/in/milda-bandzevi%C4%8Di%C5%ABt%C4%97-b0b6baba/',msg:'Hi Milda, saw you attended Config 2025 — design systems were a big theme there. I\'m exploring Hostinger\'s Senior DS Designer opening. You\'re on the design team — would you be up for a quick chat about how the system is structured today? I bring 10yr DS + multi-brand token experience.'},
    {name:'Tomas Mockevicius',title:'Former Senior Product Designer, Hostinger (now Klix.app)',type:'Peer',linkedin:'https://www.linkedin.com/in/tomasmockevicius/',msg:'Hi Tomas, I see you spent time at Hostinger\'s product design guild — I\'m exploring their Senior DS Designer opening. Would you have 15min to share how the team worked and what the DS looked like when you were there? Happy to swap notes on design systems — I\'ve done 10yr of it.'},
  ],
  '005': [
    {name:'Maggie Landers',title:'Global Talent Acquisition Lead',type:'Recruiter',linkedin:'https://www.linkedin.com/in/maggiecohenlanders/',msg:'Hi Maggie — I came across the Staff Design Systems Designer role at Harvey. I spent 5 years building Vio.com\'s multi-brand token architecture (Token Studio + Figma + GitHub) and just read your Jan 2026 DS rebuild post — the semantic token + Figma API sync approach is exactly what I work with. CET-based EU citizen, open to London. Worth a chat?'},
    {name:'Philip Cerles',title:'Designer, Harvey DS Team',type:'Peer',linkedin:'https://www.linkedin.com/in/philipcerles/',msg:'Hi Philip — read the Harvey DS rebuild post (Jan 2026) — the semantic token architecture + Figma API GitHub sync is the same stack I run at Vio.com. I\'m interviewing for the Staff DS role and wanted to connect with someone doing the work. Happy to exchange notes on token governance at scale if you\'re open to it.'},
    {name:'Bjørn Rostad',title:'Engineer/Designer, Harvey DS Team',type:'Peer',linkedin:'https://www.linkedin.com/in/bjornrostad/',msg:'Hi Bjørn — came across your work on Harvey\'s DS rebuild (the Figma→GitHub Action token sync in particular). I\'m applying for the Staff DS Designer role — I\'ve built similar pipelines at Vio.com with Token Studio. Would love to hear your take on what challenges remain on the code side.'},
    {name:'Aatish Nayak',title:'VP of Creative',type:'Hiring Manager',linkedin:'https://www.linkedin.com/in/aatishn/',msg:'Hi Aatish — applying for the Staff DS Designer role at Harvey. The Jan 2026 DS rebuild post shows Harvey is serious about token architecture and design-code parity — that\'s my core expertise (5yr multi-brand DS at Vio.com, Token Studio + Figma + GitHub at scale). Would love to hear how you\'re thinking about DS ownership at Harvey\'s next growth stage.'},
  ],
  '010': [
    {name:'Kir Romanovsky',title:'Design System Designer',type:'Peer',linkedin:'https://www.linkedin.com/posts/kirromanovskiy_xsolla-design-system-designer-activity-7445476050022604801-Ok2C',msg:'Saw your DS Designer post at Xsolla — I\'m applying for the same role. 10yr DS background, Token Studio + multi-brand token architecture at Vio.com. Would love 10min to hear how the ZK UI Kit team works. Worth a quick chat?'},
    {name:'Igor Starkov',title:'Senior Product Designer',type:'Peer',linkedin:'https://www.linkedin.com/in/igor-starkov-2938b795/',msg:'Applying for the DS Designer role at Xsolla. 10yr DS experience — multi-brand tokens, Token Studio + Figma + GitHub. Curious how design and the DS team collaborate there. Would a quick conversation be ok?'},
    {name:'Kira Kosmacheva',title:'Senior Frontend Dev, Design System product',type:'Peer',linkedin:'https://www.linkedin.com/in/kira-kosmacheva/',msg:'Applying for DS Designer at Xsolla. I work at the Figma↔code boundary — Token Studio, structured token JSON, GitHub sync. Would love to hear how the DS front-end layer works with the design side there. Open to a quick chat?'},
    {name:'Thomas Hansen',title:'Recruiter',type:'Recruiter',linkedin:'https://www.linkedin.com/in/thomas-hansen531/',msg:'Hi Thomas — I applied for the Design System Designer role at Xsolla. 10yr DS experience: multi-brand token architecture, Token Studio + Figma + GitHub, white-label theming at scale. Happy to share more if useful. Is this role still active?'},
  ],
  '003': [
    {name:'Chris Jennings',title:'Co-Founder & Chief Creative Officer',type:'Hiring Manager',linkedin:'https://www.linkedin.com/in/chriskjennings/',msg:'Chris — Sentry\'s "Scraps" system is doing real work (React components + design engineering). Curious how you\'re handling token governance as the product surface grows. I spent 5yr building multi-brand token architectures at Vio.com with Figma↔GitHub sync. Happy to swap notes if useful.'},
    {name:'Jocelyne Benito',title:'Recruiter',type:'Recruiter',linkedin:'https://www.linkedin.com/in/jocelynebenito/',msg:'Hi Jocelyne — I saw the Senior Product Designer, Design Systems role. 5yr building token systems (Token Studio + Figma + GitHub), EU citizen, CET. My work lives at designsystemwizard.com. Happy to share my CV if this profile fits what you\'re looking for.'},
    {name:'Ivy Sanders Schneider',title:'Senior Product Designer',type:'Peer',linkedin:'https://www.linkedin.com/in/ivy-sanders-schneider/',msg:'Ivy — read your Sentry Rollback post. The Hackweek-to-shipped arc is a good lens on how a DS team earns product trust. I\'m curious how Scraps handles documentation ownership — design team, design eng, or shared? Working through the same question for a multi-brand system.'},
    {name:'Jesse Box',title:'Senior Product Designer',type:'Peer',linkedin:'https://www.linkedin.com/in/jesse-box-835346b7/',msg:'Jesse — you\'ve been at Sentry through a period when the product got significantly more complex. Curious how the component library has kept pace — do design and engineering iterate on Scraps together, or does DS work tend to run ahead of/behind eng cadence?'},
  ],
  '006': [
    {name:'Haya Odeh',title:'Co-Founder & VP of Design',type:'Hiring Manager',linkedin:'https://www.linkedin.com/in/haya-odeh-b0725928',msg:'Haya — the "Better Tokens" post on RUI is a good articulation of the semantic layer problem. At Vio.com I ran a similar migration: single component library, brand overrides via Token Studio + GitHub sync across 5 products. Would love to hear how Replit is thinking about token governance at the Agent scale.'},
    {name:'Rob Patterson',title:'Senior Technical Recruiter',type:'Recruiter',linkedin:'https://www.linkedin.com/in/rob-patterson15/',msg:'Hi Rob — I\'m applying for the Staff Product Designer, Design System role. 5yr Token Studio + Figma↔GitHub pipeline, EU citizen (Poland, CET). Built multi-brand token systems for 5 products at Vio.com. Portfolio: designsystemwizard.com. Happy to share CV if Replit hires EU-based.'},
    {name:'Zade Kaylani',title:'Product Designer',type:'Peer',linkedin:'https://www.linkedin.com/in/zadekaylani/',msg:'Zade — saw your work on the Figma templates and SFGuesser. Curious how Replit\'s RUI token layer handles theming at the component level — do you use Figma Variables scoped to component sets, or is it a flat token namespace? Working through a similar architecture for a multi-brand system.'},
    {name:'Victoria Kim',title:'Product Designer',type:'Peer',linkedin:'https://www.linkedin.com/in/victoriasekim/',msg:'Victoria — your "Designing products for AI" talk touched on the interface challenges of non-deterministic output. Curious how Replit\'s design system has adapted to support Agent UI patterns — are you extending RUI components for agent states, or designing outside the system?'},
  ],
  '007': [
    {name:'Peter Welinder',title:'VP of Product & Partnerships',type:'Hiring Manager',linkedin:'https://www.linkedin.com/in/welinder',msg:'Running DS governance across AI product teams is a genuinely new problem — component lifespan measured in model releases, not design iterations. I\'ve owned multi-brand token architecture at Vio.com for 5yr. Curious how your team is thinking about system versioning across ChatGPT surfaces.'},
    {name:'Cary Hudson',title:'Design Director',type:'Hiring Manager',linkedin:'https://www.linkedin.com/in/cary-hudson-9964a72a/',msg:'Your POV Budapest talk on OpenAI\'s design systems — specifically governing craft at a company where the product surface keeps expanding — maps exactly to a problem I worked through at Vio.com (multi-brand token architecture, single library, three product lines). Happy to share how we approached contribution governance there.'},
    {name:'Bobby Morgan',title:'Member of People Staff, Product Design & Creative Recruiting',type:'Recruiter',linkedin:'https://www.linkedin.com/in/bobbymorgan/',msg:'Hi Bobby — I\'m a design systems specialist with 10yr experience, 5yr leading multi-brand token architecture at Vio.com. Saw OpenAI\'s DS Manager role (Ashby, job 799c9532). EU citizen, happy to relocate to SF. Happy to share CV if useful.'},
    {name:'Karolis Kosas',title:'Member of Design Staff',type:'Peer',linkedin:'https://www.linkedin.com/in/karoliskosas/',msg:'Karolis — you mentioned the competitive edge goes to those who design systems, not just products. At Vio.com I mapped that to AI-native workflows: Token Studio → GitHub → multi-brand token sync without designer-to-dev handoff friction. Curious whether that problem looks different from inside an AI lab.'},
  ],
  '008': [
    {name:'Russ d\'Sa',title:'Co-Founder & CEO',type:'Hiring Manager',linkedin:'https://www.linkedin.com/in/russelldsa',msg:'Russ — you\'re building infra for voice AI agents, but the design surface (tokens, components, docs) still needs to move as fast as the SDK. At Vio.com I owned the Figma↔GitHub token pipeline that kept designers and engineers in sync across three brand lines. Curious how that challenge looks from LiveKit\'s side.'},
    {name:'David Zhao',title:'Co-Founder & CTO',type:'Peer',linkedin:'https://www.linkedin.com/in/davidzhao/',msg:'David — I\'ve been following LiveKit\'s design system work (design.livekit.io). The token + component architecture for a developer-facing product is a distinct problem from consumer DS. I\'ve built a Figma→GitHub token pipeline at Vio.com that kept dev and design in sync. Happy to compare notes.'},
    {name:'Mathew Kamkar',title:'LiveKit (Engineering / Product)',type:'Peer',linkedin:'https://www.linkedin.com/in/matkam/',msg:'Mathew — I\'ve been digging into LiveKit\'s design system (design.livekit.io) while considering the DS engineer role. Your AWS infrastructure post was useful context. Is the DS role on the product-eng side or sits within a separate design org?'},
  ],
  '009': [
    {name:'Clay Reinken',title:'Former Director of Product Design',type:'Peer',linkedin:'https://www.linkedin.com/in/clayreinken/',msg:'Clay — I\'m looking at Zip\'s DS role (Ashby) and noticed you built the design practice there. I\'ve run multi-brand DS architecture at Vio.com for 5yr (Token Studio + Figma + GitHub sync). Any context on what the team is actually prioritising right now in DS would be genuinely useful. Happy to share more about my background.'},
    {name:'Ali Noor',title:'Founding Recruiter EMEA',type:'Recruiter',linkedin:'https://uk.linkedin.com/in/iamhiring',msg:'Hi Ali — I\'m a design systems specialist (10yr, 5yr at Vio.com) looking at Zip\'s Senior DS Designer role. I\'m EU-based but the role mentions remote possibility. Are you the right person to talk to, or can you point me to who\'s handling this hire? Happy to share CV.'},
    {name:'Melanie Hambarsoomian',title:'Director of Product Design (ANZ)',type:'Peer',linkedin:'https://www.linkedin.com/in/melanie-hambarsoomian/',msg:'Melanie — your talk on design maturity in scale-up orgs resonated. I\'ve worked through similar questions at Vio.com — building a DS that could support three brand lines without fragmenting the component library. The governance model was the hard part. Curious how Zip approaches that across a global design team.'},
    {name:'Rujul Zaparde',title:'Co-Founder & CEO',type:'Hiring Manager',linkedin:'https://www.linkedin.com/in/rujul-zaparde/',msg:'Rujul — B2B procurement UI has a specific DS problem: complex multi-team component ownership, not just consumer polish. I\'ve run that at Vio.com (multi-brand, multi-team, Token Studio + GitHub governance). Zip\'s DS role seems like a direct match. Would you be able to connect me with the right design lead?'},
  ],
  '011': [
    {name:'Miklu Silvanto',title:'Chief Design Officer',type:'Hiring Manager',linkedin:'https://www.linkedin.com/in/silvanto/',msg:'Miklu — building a DS that spans a consumer ring, a health app, and emerging enterprise surfaces is a genuinely hard multi-surface problem. I spent 5 years doing this in travel at Vio.com (multi-brand tokens, Token Studio + GitHub sync). Would love a 15-min call to compare notes on governance models at that scale.'},
    {name:'Ginny Cheng',title:'Global Head of Talent + Talent Branding',type:'Recruiter',linkedin:'https://www.linkedin.com/in/ginnycheng/',msg:'Hi Ginny — I\'m a design systems specialist (5yr, multi-brand tokens, Token Studio) interested in the DS role at Oura. I\'m EU-based (Poland, CET) — is there a remote pathway for the right candidate, or is SF hybrid a firm requirement? Happy to share my CV either way.'},
    {name:'James Zheng',title:'Senior Product Designer',type:'Peer',linkedin:'https://www.linkedin.com/in/chuofandesign/',msg:'James — curious how Oura handles the DS split between the ring hardware aesthetics and the app layer. I\'ve been dealing with similar cross-surface token challenges in travel (Vio.com, multi-brand). Is there a shared token foundation, or do hardware and software design systems live separately?'},
  ],
  '012': [
    {name:'Amber Cartwright',title:'VP of UX',type:'Hiring Manager',linkedin:'https://www.linkedin.com/in/ambercartwright/',msg:'Amber — building a design system for a travel marketplace has specific constraints most DS work doesn\'t: multi-locale, supplier variability, trust signal patterns. I spent 5yr doing exactly this at Vio.com. Would love 15 min to compare how you\'re approaching governance at GYG\'s scale.'},
    {name:'Cansu Tecimer',title:'Product Design Manager (Design Systems lead)',type:'Peer',linkedin:'https://www.linkedin.com/in/cansu-tecimer-a3458b47/',msg:'Cansu — I read your piece on integrating design into mission teams. I\'m a DS specialist with 5yr in travel (Vio.com, multi-brand tokens). Travel DS has a weird challenge: supplier content variability means components need more defensive states than most. How are you handling that pattern at GYG?'},
    {name:'Amy Williams',title:'Senior Product Designer',type:'Peer',linkedin:'https://www.linkedin.com/in/amy-williams-product-designer/',msg:'Amy — curious about the design system experience from a product designer\'s side at GYG. I\'m coming from 5yr DS work in travel (Vio.com) and trying to understand how well-adopted the Compass system is in day-to-day product work. What\'s the biggest friction point?'},
  ],
  '013': [
    {name:'Amber Cartwright',title:'VP of UX',type:'Hiring Manager',linkedin:'https://www.linkedin.com/in/ambercartwright/',msg:'Amber — I\'m a DS specialist with 5yr in travel (Vio.com, multi-brand tokens). The B2C PD role caught my eye given the domain match, though I suspect the Systems Designer role is a closer fit. Either way — would love a quick call to understand what you\'re building on the design side at GYG.'},
    {name:'Cansu Tecimer',title:'Product Design Manager',type:'Peer',linkedin:'https://www.linkedin.com/in/cansu-tecimer-a3458b47/',msg:'Cansu — I read your piece on integrating design into mission teams. I\'m a DS specialist with 5yr in travel (Vio.com, multi-brand tokens). Travel DS has a weird challenge: supplier content variability means components need more defensive states than most. How are you handling that pattern at GYG?'},
    {name:'Amy Williams',title:'Senior Product Designer',type:'Peer',linkedin:'https://www.linkedin.com/in/amy-williams-product-designer/',msg:'Amy — curious about the design system experience from a product designer\'s side at GYG. I\'m coming from 5yr DS work in travel (Vio.com) and trying to understand how well-adopted the Compass system is in day-to-day product work. What\'s the biggest friction point?'},
  ],
  '014': [
    {name:'Manuel Munoz Solera',title:'VP of Design',type:'Hiring Manager',linkedin:'https://www.linkedin.com/in/mamuso/',msg:'Vercel\'s v0 made me rethink the design-to-code handoff entirely. At Vio.com I built a Figma↔GitHub token sync pipeline (Token Studio + Style Dictionary) that cut DS drift to near-zero across 3 brands. How is your team thinking about the boundary between design tooling and the actual codebase?'},
    {name:'Lydia Cuarezma-Cobette',title:'Senior Technical Recruiter',type:'Recruiter',linkedin:'https://www.linkedin.com/in/lydiacuarezma/',msg:'10 years in design systems, 5 at Vio.com owning multi-brand token architecture (Token Studio + Figma + GitHub sync). EU citizen, CET, open to Berlin anchor days. Seeing the Sr Product Designer role — happy to share my CV if the profile fits what you\'re looking for.'},
    {name:'Pablo Stanley',title:'Staff Product Designer (v0)',type:'Peer',linkedin:'https://www.linkedin.com/in/pablostanley1/',msg:'Your v0 workflow posts changed how I think about prompt-to-UI iteration. I\'ve been using it alongside Token Studio to prototype DS components — the gap between design intent and code output is shrinking fast. What\'s the biggest constraint you\'re still hitting in that loop?'},
    {name:'Henry Heffernan',title:'Senior Design Engineer',type:'Peer',linkedin:'https://www.linkedin.com/in/henryheffernan/',msg:'Your portfolio work on Turborepo visualizations is exactly the kind of design-engineering overlap I find most interesting. I\'ve been building token pipelines where Figma is the source of truth for the codebase — curious how you think about the DS layer at Vercel\'s scale.'},
  ],
  '015': [
    {name:'Manuel Munoz Solera',title:'VP of Design',type:'Hiring Manager',linkedin:'https://www.linkedin.com/in/mamuso/',msg:'Vercel\'s v0 made me rethink the design-to-code handoff entirely. At Vio.com I built a Figma↔GitHub token sync pipeline (Token Studio + Style Dictionary) that cut DS drift to near-zero across 3 brands. How is your team thinking about the boundary between design tooling and the actual codebase?'},
    {name:'Lydia Cuarezma-Cobette',title:'Senior Technical Recruiter',type:'Recruiter',linkedin:'https://www.linkedin.com/in/lydiacuarezma/',msg:'10 years in design systems, 5 at Vio.com owning multi-brand token architecture (Token Studio + Figma + GitHub sync). EU citizen, CET, open to Berlin anchor days. Seeing the Sr Product Designer role — happy to share my CV if the profile fits what you\'re looking for.'},
    {name:'Pablo Stanley',title:'Staff Product Designer (v0)',type:'Peer',linkedin:'https://www.linkedin.com/in/pablostanley1/',msg:'Your v0 workflow posts changed how I think about prompt-to-UI iteration. I\'ve been using it alongside Token Studio to prototype DS components — the gap between design intent and code output is shrinking fast. What\'s the biggest constraint you\'re still hitting in that loop?'},
    {name:'Henry Heffernan',title:'Senior Design Engineer',type:'Peer',linkedin:'https://www.linkedin.com/in/henryheffernan/',msg:'Your portfolio work on Turborepo visualizations is exactly the kind of design-engineering overlap I find most interesting. I\'ve been building token pipelines where Figma is the source of truth for the codebase — curious how you think about the DS layer at Vercel\'s scale.'},
  ],
  '016': [
    {name:'Caitlin Whiteman',title:'Director, Recruiting',type:'Recruiter',linkedin:'https://www.linkedin.com/in/caitlinwhiteman/',msg:'Hi Caitlin, I\'m a design systems specialist based in Poland (EU). The Denver PD role requires US auth I don\'t have, but Contentful\'s Berlin hub is interesting. Is the design team hiring EU-based or remote talent? Happy to share context on my work with multi-brand token systems.'},
    {name:'Eoin Crowley',title:'Product Designer',type:'Peer',linkedin:'https://www.linkedin.com/in/eoincrowley/',msg:'Hi Eoin, designing for a CMS-native audience is a genuinely different problem — content editors have very different mental models than typical app users. I work on design systems and I\'m curious how Forma 36 balances editor-focused patterns with developer extensibility. Would love to swap notes.'},
    {name:'Fabian Schultz',title:'formerly Staff Product Designer (Forma 36 lead), now at GitHub',type:'Peer',linkedin:'https://www.linkedin.com/in/fabian-schultz/',msg:'Hi Fabian, I\'ve followed Forma 36\'s evolution — the accessible color palette work was well executed. I build multi-brand token systems (Token Studio + Figma + GitHub sync). Curious how you approached DS governance when Contentful was scaling. Any lessons that didn\'t make the blog posts?'},
  ],
  '017': [
    {name:'Zach Krall',title:'Head of Design',type:'Hiring Manager',linkedin:'https://www.linkedin.com/in/zachkrall/',msg:'Hi Zach, designing UI for emotional voice AI is a genuinely unsolved problem — most conversational interfaces still rely on chat metaphors that don\'t match the medium. I work on design systems and I\'m thinking about how DS components need to change when the primary interaction is spoken. Would value your perspective.'},
    {name:'Zach Greathouse',title:'Hume AI (Product/Growth)',type:'Peer',linkedin:'https://www.linkedin.com/in/zach-greathouse/',msg:'Hi Zach, I\'m exploring how design systems need to evolve for AI-native products — especially when the primary output is voice or emotion data rather than pixels. Hume\'s work is one of the more interesting cases. What\'s the product team\'s design collaboration look like day-to-day?'},
    {name:'Alan Cowen',title:'CEO / Founder',type:'Hiring Manager',linkedin:'https://www.linkedin.com/in/alan-cowen/',msg:'Hi Alan, Hume\'s work on mapping emotional expression to AI response is fascinating from a design angle too — how do you represent uncertainty or confidence in a voice interface without visual fallbacks? I design systems for complex products and this is a problem I keep coming back to. Any thoughts?'},
  ],
  '018': [
    {name:'Ashley Youett',title:'Director of Design',type:'Hiring Manager',linkedin:'https://www.linkedin.com/in/ashleyyouett/',msg:'Ashley — building a DS for voice + chat interfaces simultaneously is one of the harder multimodal UX problems I\'ve seen. I\'ve done this at scale for Vio.com across 3 brands with Token Studio. The Consumer Experience role caught my eye. Would love to hear what that challenge looks like from your side.'},
    {name:'Samantha Lisik',title:'Senior Talent Acquisition Partner',type:'Recruiter',linkedin:'https://www.linkedin.com/in/samanthalisik/',msg:'Samantha — saw both Staff Product Designer roles at Parloa (Consumer + Expert Experience). 10 yrs design systems, multi-brand token architecture at Vio.com, Token Studio + Figma + GitHub pipeline. EU citizen, CET. Happy to share portfolio if either role fits — designsystemwizard.com.'},
    {name:'Martina Nikolova',title:'Senior Product Designer',type:'Peer',linkedin:'https://www.linkedin.com/in/martina-nikolova-product-designer/',msg:'Martina — I\'ve been reading about what Parloa is building and the design challenges around voice + chat unification seem genuinely interesting. I work in design systems (multi-brand, Token Studio). Curious how the team thinks about DS coherence across those different interaction modes.'},
  ],
  '019': [
    {name:'Ashley Youett',title:'Director of Design',type:'Hiring Manager',linkedin:'https://www.linkedin.com/in/ashleyyouett/',msg:'Ashley — building a DS for voice + chat interfaces simultaneously is one of the harder multimodal UX problems I\'ve seen. I\'ve done this at scale for Vio.com across 3 brands with Token Studio. The Consumer Experience role caught my eye. Would love to hear what that challenge looks like from your side.'},
    {name:'Samantha Lisik',title:'Senior Talent Acquisition Partner',type:'Recruiter',linkedin:'https://www.linkedin.com/in/samanthalisik/',msg:'Samantha — saw both Staff Product Designer roles at Parloa (Consumer + Expert Experience). 10 yrs design systems, multi-brand token architecture at Vio.com, Token Studio + Figma + GitHub pipeline. EU citizen, CET. Happy to share portfolio if either role fits — designsystemwizard.com.'},
    {name:'Martina Nikolova',title:'Senior Product Designer',type:'Peer',linkedin:'https://www.linkedin.com/in/martina-nikolova-product-designer/',msg:'Martina — I\'ve been reading about what Parloa is building and the design challenges around voice + chat unification seem genuinely interesting. I work in design systems (multi-brand, Token Studio). Curious how the team thinks about DS coherence across those different interaction modes.'},
  ],
  '020': [
    {name:'Marcel Gordon',title:'VP Product',type:'Hiring Manager',linkedin:'https://www.linkedin.com/in/marcel-gordon/',msg:'Marcel — I\'ve been following Helsing\'s growth. Building design systems for high-stakes, complex interfaces (operational dashboards, config tools) is what I do — 10 yrs, multi-brand token architecture at Vio.com. The Deployed PD role is a stretch for me, but curious if Helsing has any design platform or DS infrastructure work on the horizon.'},
    {name:'Suzanne Diamond',title:'Director of Talent Acquisition (now AI Chief of Staff & Ops)',type:'Recruiter',linkedin:'https://www.linkedin.com/in/suzanne-diamond-b528a0aa/',msg:'Suzanne — saw the Deployed Product Designer role at Helsing. That specific role is a stretch for my profile (I\'m a design systems specialist), but wanted to flag interest in the company. Is there a more systems-focused or platform design track at Helsing currently or coming up?'},
    {name:'Hollie Carwardine',title:'People Operations Specialist',type:'Recruiter',linkedin:'https://www.linkedin.com/in/hollie-carwardine/',msg:'Hollie — I came across the Deployed Product Designer role at Helsing. My background is design systems rather than field-deployed work, but I\'m interested in Helsing\'s mission. Could you point me to whoever\'s hiring for design platform or DS roles, if those exist?'},
  ],
  '021': [
    {name:'Dmitry Scheglov',title:'Head of Product Design',type:'Hiring Manager',linkedin:'https://www.linkedin.com/in/goldfinch/',msg:'Dmitry — scaling design across 18 markets with a single mobile app and now cards + web surfaces is exactly the kind of DS challenge I work on. Built multi-brand token architecture at Vio.com (Token Studio + Figma + GitHub). The Senior PD mobile role is a stretch for me, but curious if there\'s a DS or platform design track in your plans.'},
    {name:'Ben George',title:'Product Design Lead',type:'Hiring Manager',linkedin:'https://www.linkedin.com/in/uxbengeorge/',msg:'Ben — saw your Shopify background and the work at Trade Republic. I\'m a design systems specialist (multi-brand token architecture, Token Studio) and Trade Republic\'s cross-market scale is exactly the kind of DS problem I find interesting. The mobile PD role isn\'t my core fit, but wanted to connect — design systems context seems relevant to what you\'re building.'},
    {name:'Carolin Osthoff',title:'Senior Product Designer',type:'Peer',linkedin:'https://www.linkedin.com/in/carolin-osthoff-082a97188/',msg:'Carolin — watched your George UX Conference talk about design at Trade Republic. Interesting challenge designing for a primarily mobile-first trading product at that market scale. I work in design systems — curious how the team handles consistency across 18 markets. Any shared tokens / component library?'},
  ],
  '022': [
    {name:'Aparna Dhinakaran',title:'Co-Founder & Chief Product Officer',type:'Hiring Manager',linkedin:'https://www.linkedin.com/in/aparnadhinakaran',msg:'Arize\'s observability UI handles complex ML data in a way that actually makes sense to practitioners — that\'s hard to do. I\'ve built DS infrastructure where Figma tokens compile directly to code (Token Studio → Style Dictionary). For a tooling product like Phoenix, is the DS layer a current focus or still in backlog?'},
    {name:'Meredith M.',title:'Talent Acquisition',type:'Recruiter',linkedin:'https://www.linkedin.com/in/meredithmende/',msg:'10 years in design systems, most recently owning multi-brand token architecture at Vio.com (Token Studio, Figma↔GitHub sync). Seeing the UX Designer role at Arize — my DS work produces code-ready outputs, which addresses the engineering adjacency requirement. Happy to share CV.'},
    {name:'Jason Lopatecki',title:'Co-Founder & CEO',type:'Hiring Manager',linkedin:'https://www.linkedin.com/in/jason-lopatecki-9509941',msg:'Arize\'s bet on evaluation-driven AI development maps directly to how I think about DS: measure, iterate, make it the floor not the ceiling. I\'m exploring roles where design infrastructure has real product impact. Is the UX Designer search still active?'},
  ],
  '023': [
    {name:'Rafael Ferreira',title:'Design Manager',type:'Hiring Manager',linkedin:'https://www.linkedin.com/in/rafaelgfest6/',msg:'DS experience is rare in the JD for a Sr PD role — noticed you\'re explicitly asking for it at Amplemarket. I built multi-brand token architecture at Vio.com (Token Studio + Figma + GitHub sync, 3 brands). What\'s the DS state you\'re trying to get to, and what\'s blocking it right now?'},
    {name:'Miguel Cruz',title:'Senior Designer & Creative Coder',type:'Peer',linkedin:'https://www.linkedin.com/in/miguelcruzdesign/',msg:'Your Onda Studio work crossed my feed — the computational approach to visual identity is something I keep coming back to. I\'m exploring similar territory from the DS side: using code-generated tokens to enforce consistency across Figma and the codebase. Curious what tools you\'re using at Amplemarket for that layer.'},
    {name:'Micael Oliveira',title:'Co-Founder & CRO',type:'Hiring Manager',linkedin:'https://www.linkedin.com/in/micaelol/',msg:'Amplemarket\'s UX is unusually coherent for a sales tool at this scale — the DS work underneath shows. I\'ve been building multi-brand token systems at Vio.com for 5 years and am looking at EMEA remote roles where DS is taken seriously. Is the Sr PD search still active?'},
  ],
  '024': [
    {name:'Jaime Mariko McFarland',title:'Head of Design',type:'Hiring Manager',linkedin:'https://www.linkedin.com/in/jaime-mariko-mcfarland-32780b44/',msg:'Hi Jaime, the SF-only constraint means I can\'t apply to the current PD role (I\'m Poland-based), but Airtable\'s DS work is one of the more interesting cases at scale — complex relational data, non-technical users, AI layer on top. If a remote or EU-friendly DS role opens, I\'d want to be on your radar. Happy to share context.'},
    {name:'Erin Woo',title:'Product Designer',type:'Peer',linkedin:'https://www.linkedin.com/in/wooerin/',msg:'Hi Erin, building DS for a product like Airtable — where the data model is user-defined and infinite — seems like a fascinating constraint. I\'ve worked on multi-brand token systems for hospitality (Vio.com) and I keep thinking about how you handle component variance when the base data layer is unpredictable. How do you approach that?'},
    {name:'Joe Callina',title:'Recruiter',type:'Recruiter',linkedin:'https://www.linkedin.com/in/joecallinarecruiter/',msg:'Hi Joe, the current PD role requires SF on-site and I\'m based in Poland — hard constraint. But Airtable\'s design culture is genuinely appealing. Do any design or design systems roles at Airtable accommodate remote/EU-based candidates? Happy to share background if there\'s a relevant pipeline.'},
  ],
};
